apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-scheduler
  labels:
    app: random-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-scheduler
  template:
    metadata:
      labels:
        app: random-scheduler
    spec:
      #由于阿里云上自己搭建的集群跨节点通信不通, 否则报dial tcp 10.96.0.1:443: i/o timeout
      nodeSelector:
        role: master 
      serviceAccount: random-scheduler
      containers:
        - name: random-scheduler
          image: mospany/random-scheduler:v0.3
          imagePullPolicy: Always
